#!/bin/bash

set -e

DRYRUN=

if [ -z "$HOME" ]; then
  echo 'Your $HOME is unset!'
  exit 1
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

BASE_SCRIPT_DIR=$(basename $SCRIPT_DIR)
echo $BASE_SCRIPT_DIR

IFS=$'\n'

mkdir -p "$HOME/src"
pushd src
for dotfile in $(find . -maxdepth 1 ! -path .) ; do
  FILENAME=$(basename $dotfile)
  SRC=$BASE_SCRIPT_DIR/src/$FILENAME
  DST=$HOME/src/$FILENAME
  if [ ! -e "$HOME/$SRC" ]; then echo could not find "$SRC"; exit 1; fi
  $DRYRUN rm -rf "$DST"
  $DRYRUN ln -s "../$SRC" "$DST"
done
popd
echo

for dotfile in $(find . -maxdepth 1 ! -path ./.git ! -path ./.gitignore ! -path ./.gitmodules -regex '.*/\..+') ; do
  FILENAME=$(basename $dotfile)
  SRC=$BASE_SCRIPT_DIR/$FILENAME
  DST=$HOME/$FILENAME
  if [ ! -e "$HOME/$SRC" ]; then echo could not find "$SRC"; exit 1; fi
  $DRYRUN rm -rf "$DST"
  $DRYRUN ln -s "$SRC" "$DST"
done
echo

mkdir -p "$HOME/.config"
pushd config
for dotfile in $(find . -maxdepth 1 ! -path .) ; do
  FILENAME=$(basename $dotfile)
  SRC=$BASE_SCRIPT_DIR/config/$FILENAME
  DST=$HOME/.config/$FILENAME
  if [ ! -e "$HOME/$SRC" ]; then echo could not find "$SRC"; exit 1; fi
  $DRYRUN rm -rf "$DST"
  $DRYRUN ln -s "../$SRC" "$DST"
done
popd
echo

echo "export PATH=$HOME/$BASE_SCRIPT_DIR/bin:\$PATH" > "$SCRIPT_DIR/.bash.d/add_dot_extra_paths.sh"

################################################################################

if [ -z "$1" ]; then
  echo 'did not request machine specific config files, exiting'
  exit 0
fi

pushd "machines/$1"
for dotfile in $(find . -maxdepth 1 -regex '.*/\..+') ; do
  FILENAME=$(basename $dotfile)
  SRC=$BASE_SCRIPT_DIR/machines/$1/$FILENAME
  DST=$HOME/$FILENAME
  if [ ! -e "$HOME/$SRC" ]; then echo could not find "$SRC"; exit 1; fi
  $DRYRUN rm -rf "$DST"
  $DRYRUN ln -s "$SRC" "$DST"
done
popd
echo
