# Run the below command when you edit .drone.yml
#   drone secure --repo vim-jp/vital.vim --in .drone.sec.yaml
#
build:
  lint:
    image: haya14busa/lint-vital.vim:0.9.5
    environment:
      - REVIEWDOG_GITHUB_API_TOKEN=$$REVIEWDOG_GITHUB_API_TOKEN
    commands:
      - go get -d -v ./scripts
      - curl -L -o ./install-misspell.sh https://git.io/misspell && sh ./install-misspell.sh -b /usr/local/bin
      - reviewdog -ci=droneio
    when:
      event: pull_request
